blank_issues_enabled: true
contact_links:
   - name: [CoE Starter Kit] Ideas
     url: https://github.com/microsoft/coe-starter-kit/discussions/categories/coe-starter-kit-ideas
     about: Please suggest ideas to improve the CoE Starter Kit here.
   - name: [CoE Starter Kit] Questions
     url: https://github.com/microsoft/coe-starter-kit/discussions/categories/coe-starter-kit-q-a
     about: Please ask and answer questions about the CoE Starter Kit here.
   - name: [ALM Accelerator] Ideas
     url: https://github.com/microsoft/coe-starter-kit/discussions/categories/alm-ideas
     about: Please suggest ideas to improve the ALM Accelerator here.
   - name: [ALM Accelerator] Questions
     url: https://github.com/microsoft/coe-starter-kit/discussions/categories/alm-q-a
     about: Please ask and answer questions about the ALM Accelerator here.
   - name: Report a security vulnerability
     url: https://github.com/microsoft/coe-starter-kit/security/policy
     about: Please review our security policy for more details.
