parameters:
- name: serviceConnection
  type: string
- name: environmentName
  type: string

steps:
- pwsh: |
   $path = "$(Pipeline.Workspace)/drop/ConfigurationMigrationData-${{parameters.environmentName}}.zip"
   if(Test-Path $path)
   {
        Write-Host "##vso[task.setvariable variable=ConfigurationMigrationFilePath]$path"
   }
   else
   {
        $path = "$(Pipeline.Workspace)/drop/ConfigurationMigrationData.zip"
        if(Test-Path $path)
        {
            Write-Host "##vso[task.setvariable variable=ConfigurationMigrationFilePath]$path"
        }
        else
        {
            Write-Host "##vso[task.setvariable variable=ConfigurationMigrationFilePath]"
        }
   }
  displayName: 'Check if Configuration Migration Data exists'

- powershell: |
    $microsoftConfigurationMigrationPowerShellModule = '$(CoETools_Microsoft_Xrm_Tooling_ConfigurationMigration)'
    Import-Module $microsoftConfigurationMigrationPowerShellModule -RequiredVersion $(configurationMigrationPowerShellVersion) -Force
    Import-CrmDataFile -CrmConnection "$(connectionVariables.BuildTools.DataverseConnectionString)" -Datafile "$(ConfigurationMigrationFilePath)" -Verbose
  displayName: 'Import Configuration Migration Data'
  condition: and(succeeded(), ne(variables['ConfigurationMigrationFilePath'], ''))
  #skip task if there is no ConfigurationMigrationData in the downloaded artifact