parameters:
- name: variableName
  type: string
- name: deploymentSettingsPath
  type: string
- name: deploymentSettingsNode
  type: string
- name: displayName
  type: string
- name: commitScope
  type: string
  default: '1'

steps:
- pwsh: |
    . "$env:POWERSHELLPATH/build-deploy-solution-functions.ps1"
     Set-Deployment-Variable "${{parameters.deploymentSettingsPath}}" "${{parameters.deploymentSettingsNode}}" "${{parameters.variableName}}" "$(Agent.BuildDirectory)"
  displayName: ${{parameters.displayName}}
  condition: and(succeeded(), ne('${{parameters.commitScope}}', '2'))