parameters:
- name: variableName
  type: string
- name: pipelineVariableValue
  type: string
- name: deploymentSettingsPath
  type: string
- name: deploymentSettingsNode
  type: string
- name: displayName
  type: string

steps:
- powershell: |
    # The if statement below is checking to see if the variable has been set in the pipeline. If it hasn't been set the value of the variable will be the name of the variable (e.g. $(SomeDeploymentVariable) it should be safe to check for the characters '$(' to determine if it's been set
    $variableValue = ''
    if('{{parameters.deploymentSettingsPath}}' -ne '')
    {
        $deploymentSettings = Get-Content '${{parameters.deploymentSettingsPath}}' | ConvertFrom-Json
        $settingsNode = $deploymentSettings.${{parameters.deploymentSettingsNode}}
        $settingsJson = ConvertTo-Json($settingsNode) -Compress
        if ($settingsJson) {
            $variableValue = $settingsJson
        }
    }
    elseif(!'${{parameters.pipelineVariableValue}}'.Contains('$('))
    {
        $variableValue = '${{parameters.pipelineVariableValue}}'
    }
    # Set the deployment variable for use elsewhere
    Write-Host '##vso[task.setvariable variable=${{parameters.variableName}};isOutput=true]'$variableValue

  name: ${{parameters.variableName}}
  displayName: ${{parameters.displayName}}