parameters:
- name: serviceConnection
  type: string

steps:
- powershell: |    
    Import-Module Microsoft.PowerApps.Administration.PowerShell -Force -RequiredVersion $(PowerAppsAdminModuleVersion) -ArgumentList @{ NonInteractive = $true }
    Add-PowerAppsAccount -TenantID $(TenantId) -ApplicationId $(ClientId) -ClientSecret $(ClientSecret)
    Import-Module Microsoft.Xrm.Data.PowerShell -Force -RequiredVersion $(XrmDataPowerShellVersion) -ArgumentList @{ NonInteractive = $true }
    $conn = Get-CrmConnection -ConnectionString "$(CdsBaseConnectionString)${{parameters.serviceConnection}}"

    # Get the EnvironmentName (which is a GUID) of the environment based on the orgid in Dataverse
    $orgId = (Get-CrmRecords -conn $conn -EntityLogicalName organization).CrmRecords[0].organizationid

    # Get the Environment using the InstanceId
    $environment = Get-AdminPowerAppEnvironment -InstanceId $orgId
    # Get the Environment name (which is a GUID)
    $environmentId = $environment.EnvironmentName    
    # Set the EnvironmentId as a global variable for use in other templates
    echo "##vso[task.setvariable variable=EnvironmentId]$environmentId"
  displayName: 'Set EnvironmentId'