name: pr-loop

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
jobs:
  pr-loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run e2e pipeline test
        env:
          AZDO_ORG: ${{ secrets.AZDO_ORG }}
          AZDO_PROJECT: ${{ secrets.AZDO_PROJECT }}
          AZDO_REPO: ${{ secrets.AZDO_PROJECT }}
          PR_LOOP_DATA: ${{ secrets.PR_LOOP_DATA }}
          AZDO_SVC_CONN_NAME: ${{ secrets.AZDO_SVC_CONN_NAME }}
          AZDO_SVC_CONN_URL: ${{ secrets.AZDO_SVC_CONN_NAME }}
          PR_LOOP_EMAIL: ${{ secrets.PR_LOOP_EMAIL }}
          PR_LOOP_USERNAME: ${{ secrets.PR_LOOP_USERNAME }}
        run: |
          . ./.github/workflows/pr-loop.ps1
          $data = @{
              Org                   = $env:AZDO_ORG
              Project               = $env:AZDO_PROJECT
              BranchToTest          = $env:GITHUB_HEAD_REF
              SourceBranch          = 'ALMAcceleratorSampleSolution'
              BranchToCreate        = 'pr-loop-e2e-test-' + (New-Guid).Guid
              CommitMessage         = 'pr-loop-e2e-test'
              Data                  = $env:PR_LOOP_DATA 
              Email                 = $env:PR_LOOP_EMAIL
              Repo                  = $env:AZDO_REPO
              ServiceConnection     = $env:AZDO_SVC_CONN_NAME
              SolutionName          = "ALMAcceleratorSampleSolution"
              UserName              = $env:PR_LOOP_USERNAME
          }
          Invoke-EndToEndPipelineTest -User ${{ secrets.AZDO_USER }} -Password ${{ secrets.AZDO_PASSWORD }} -Data $data
        shell: pwsh
